### ISSUE TITLE
user-configured redirect URL clobbered in oauthproxy.go

### ISSUE THREAD

**Issue by dt-rush** [pusher/oauth2_proxy#9] opened 2018-12-06 16:44 UTC
see line 155 of oauthproxy.go ([link](https://github.com/pusher/oauth2_proxy/blob/master/oauthproxy.go#L155))

We literally overwrite whatever the value is with `fmt.Sprintf("%s/callback", opts.ProxyPrefix)` even if the user provided a redirect URL they want to use.

I have a PR for this which I tested and confirmed to resolve the issue. Will link.

**Comment by JoelSpeed** [comment] 2019-03-05 14:58
This is now fixed since #10 has been merged

**Comment by Ghazgkull** [comment] 2019-03-05 16:37
Awesome, thanks. For planning/adoption purposes, might I ask how soon we could expect to see a new Release available with this fix?

**Comment by JoelSpeed** [comment] 2019-03-05 16:54
There are a couple of PRs open for optimizations and bug fixes that I would like to get merged before we make a new release, hopefully this should be within the next couple of weeks

**Comment by Ghazgkull** [comment] 2019-03-07 03:57
@JoelSpeed I went ahead and tested this change today and the behavior isn't what I expected.

I thought this change would update oauth2_proxy so that it would simply hand out whatever redirect-url was configured. I expected this would allow me to configure oauth2_proxy with a redirect url independent of the proxyPrefix used for internal routing.

For example, I am running oauth2_proxy with the default proxy path... receiving all traffic under the normal `/oauth` paths... But I wanted to give out a redirect URL with the path of an external ingress which sits out in front of the proxy (a path that oauth2_proxy never sees).

But in testing and then looking at the code more closely, this change affects both the path the oauth2_proxy gives out during the oauth dance *and* it also updates the internal path routing within the proxy itself... So the external path and internal routing are still the same.

Is this the expected behavior?

**Comment by Ghazgkull** [comment] 2019-03-07 04:04
Looking at the PR (https://github.com/pusher/oauth2_proxy/pull/10/files), I feel like the change to oauthproxy.go lines 186-188 are good because they fix the proxy to hand out whatever redirect-url was configured. But the change to oauthproxy.go line 223 is incorrect; that line should have been kept the same to keep oauth2_proxy's internal routing consistent based on the proxy path.

**Comment by Ghazgkull** [comment] 2019-03-07 04:05
@dt-rush Please see my comments above. What do you think?

**Comment by Ghazgkull** [comment] 2019-03-08 20:39
@JoelSpeed Can we re-open this issue? I really think that the PR which was merged is badly flawed.

**Comment by ploxiln** [comment] 2019-03-08 20:47
I suggest opening a PR with your suggested adjustment, and having further discussion there.
(I think you're right, btw.)

**Comment by JoelSpeed** [comment] 2019-03-09 10:05
@Ghazgkull Please open a PR with your suggested change as @ploxiln has suggested and I will take a look

**Comment by Ghazgkull** [comment] 2019-03-12 03:44
@ploxiln @JoelSpeed Oh. Derp. I just opened PR 99, but I see you guys already made the change. Cheers.

**Comment by ploxiln** [comment] 2019-03-12 04:17
nope, sorry to cause confusion, that was related to my fork, which has diverged, the fix is not in this repo

**Comment by JoelSpeed** [comment] 2019-03-12 16:49
@ploxiln @Ghazgkull could you take a look at https://github.com/pusher/oauth2_proxy/pull/101 and verify that this is the change we need to make here?

**Closed** 2019-03-12 17:33 UTC
