### ISSUE TITLE
Structured logging

### ISSUE THREAD

**Issue by terala** [pusher/oauth2_proxy#90] opened 2019-03-07 00:05 UTC
Structured logging to a json line format will greatly help log collection and processing in tools like elastic, splunk, etc.

## Expected Behavior

Log lines should be done in json, so the fields end up as first class citizens within the log and allows easy log ingestion into splunk, elastic, etc. The log levels and location should be configurable so other agents can pick them up and manage them as needed. It should also allow easy management/uploading, etc through a sidecar.

## Current Behavior

Logs are sent to stdout and are not easily parsable from tools like splunk agent.

## Possible Solution

Logs should be generated in json.

## Steps to Reproduce (for bugs)

Generate output. All data is in text lines and not in json.

## Context

Most companies ingest logs into tools like splunk so they can be interpreted, aggregated, etc. Json logging makes this process very easy for ingestion and makes sure there is no data loss.

## Your Environment

My current environment is docker based.

- Version used:
latest

**Comment by JoelSpeed** [comment] 2019-05-09 09:34
Logging has recently been improved with logging formats that will allow users to define their own structure, closing this

**Closed by JoelSpeed** 2019-05-09 09:34 UTC

**Comment by max-wittig** [comment] 2020-11-16 08:00
I don't think this should be closed. json logging seems to be pretty standard these days and should be supported by oauth2-proxy

**Comment by max-wittig** [comment] 2020-11-16 08:43
We solved it in a hacky way for now, but using this logging format. Maybe this helps somebody, as long as this is not offically supported.

```config

auth_logging_format = '{"client": "{{.Client}}", "username": "{{.Username}}", "timestamp": "{{.Timestamp}}", "status": {{.Status}}, "message": "{{.Message}}"}'
request_logging_format = '{"client": "{{.Client}}", "username": "{{.Username}}", "timestamp": "{{.Timestamp}}", "host": "{{.Host}}", "request_method": "{{.RequestMethod}}", "upstream": "{{.Upstream}}", "request_uri": {{.RequestURI}}, "protocol": "{{.Protocol}}", "user_agent": {{.UserAgent}}, "status_code": {{.StatusCode}}, "response_size": {{.ResponseSize}}, "request_duration": {{.RequestDuration}}}'
standard_logging_format = '{"timestamp": "{{.Timestamp}}", "file": "{{.File}}", "message": "{{.Message}}"}'
```

**Comment by JoelSpeed** [comment] 2020-11-16 09:05
One of the primary goals of introducing customisable logging formats was to allow people to use structured logging in exactly the way you have done in your comment above.

I can't recall if we have an example of a JSON logging template in the docs, but if not, perhaps we could update it to I could your example

**Comment by Ghazgkull** [comment] 2021-02-18 20:00
@max-wittig Thank you for this example. I'm trying to figure this out right now. The format you provide looks good, but I deploy oauth2-proxy with the helm chart and helm is choking on a value like that... I think because the format string is using the same variable syntax as helm. Have you (or anyone else, @JoelSpeed) configured structured log formatting using the Helm chart?

**Comment by Ghazgkull** [comment] 2021-02-18 22:55
For anyone coming along in the future, I actually figured out how to set this up in the Helm chart. Here's an example of what I'm doing in my values.yaml:
```
extraArgs:
  request-logging-format: >-
    {
    "client":"{{.Client}}",
    "method":"{{.RequestMethod}}",
    "username":"{{.Username}}",
    "timestamp":"{{.Timestamp}}",
    "host":"{{.Host}}",
    "upstream":"{{.Upstream}}",
    "url":"{{.RequestURI}}",
    "protocol":"{{.Protocol}}",
    "user_agent":"{{.UserAgent}}",
    "status":"{{.StatusCode}}",
    "length":"{{.ResponseSize}}",
    "response-time":"{{.RequestDuration}}",
    "message":"{{.RequestMethod}} {{.RequestURI}} complete for {{.UserAgent}} in {{.ResponseDuration}}s (status:{{.StatusCode}})"
    }
```

**Comment by AlexSins** [comment] 2021-03-15 06:24
>- { "client":"", "method":"", "username":"", "timestamp":"", "host":"", "upstream":"", "url":, "protocol":"", "user_agent":, "status":"", "length":"", "response-time":"", }

maybe the problem is the lack of space between the quotes #

**Comment by Ghazgkull** [comment] 2021-03-15 16:13
@AlexSins Unfortunately, it's not an input problem. The code itself isn't written to support JSON logging because there's no way to tell it to do the required escaping (e.g. double quotes). The problem is tracked here: https://github.com/oauth2-proxy/oauth2-proxy/issues/1057
