### ISSUE TITLE
unable to run self compile  oauth2_proxy exc file in linux 

### ISSUE THREAD

**Issue by amiya-elear** [pusher/oauth2_proxy#362] opened 2020-01-23 10:08 UTC
Hi Team,

I am trying to cteate an new binary of oauth2_proxy  using latets code by adding a new provider to it.
I am able to craete new binary using golang 1.13 but after creating binary from golang container I
ran  oauth2_proxy with below config file
./oauth2_proxy \
 --email-domain="*" \
 --upstream="http://127.0.0.1:xxxx/" \
 --approval-prompt="auto" \
 --redirect-url="http://localhost:4180/oauth2/callback" \
 --cookie-secret=secretsecret \
 --cookie-name="_oauth2_proxy" \
 --cookie-secure=false \
 --provider="new_provider" \
 --client-id="xxxxx" \
 --client-secret="xxxx"

Its throwing me an error:
2020/01/23 15:20:05 ERROR: flag "cookie-samesite" does not exist
panic: ERROR: flag "cookie-samesite" does not exist

goroutine 1 [running]:
log.Panicf(0xbcb7cc, 0x1d, 0xc00023ba58, 0x1, 0x1)
	/usr/local/go/src/log/log.go:345 +0xc0
github.com/mreiferson/go-options.Resolve(0xa6dd20, 0xc0000c17d0, 0xc00008cd20, 0xc00010d1d0)
	/go/src/github.com/mreiferson/go-options/options.go:73 +0xb7b
github.com/mreiferson/go-options.Resolve(0xaccde0, 0xc0000c1600, 0xc00008cd20, 0xc00010d1d0)
	/go/src/github.com/mreiferson/go-options/options.go:54 +0xd1b
main.main()
	/go/src/github.com/amiya-elear/oauth2_proxy/main.go:154 +0x1cd5

I try to run by adding cookie-samesite all attribute option  but its throwing me 

ERROR: flag provided but not defined: -cookie-samesite 

./oauth2_proxy \
 --email-domain="*" \
 --upstream="http://127.0.0.1:xxxx/" \
 --approval-prompt="auto" \
 --redirect-url="http://localhost:4180/oauth2/callback" \
 --cookie-secret=secretsecret \
 --cookie-name="_oauth2_proxy" \
 --cookie-secure=false \
 ----cookie-samesite="none",
 --provider="new_provider" \
 --client-id="xxxxx" \
 --client-secret="xxxx"
ERROR: flag provided but not defined: -cookie-samesite 

Kindly help me to fix this issue

**Comment by ploxiln** [comment] 2020-01-23 23:48
just guessing, this is probably due to some missed detail in https://github.com/pusher/oauth2_proxy/pull/339

**Comment by JoelSpeed** [comment] 2020-01-26 17:19
Well this is a tricky one! I can see the flag is defined [here](https://github.com/pusher/oauth2_proxy/blob/master/main.go#L90), and referenced [here](https://github.com/pusher/oauth2_proxy/blob/master/pkg/apis/options/cookie.go#L15), which should allow the options to be resolved assuming the cookie name and flag tag match,

I think I'm going to have to do some deeper investigation and debugging into why this isn't working. This is urgent priority as this will block us from creating a release.

Thanks for raising to our attention @amiya-elear

**Comment by idntfy** [comment] 2020-01-28 13:20
jfyi, `-cookie-samesite=none` param works for me very well on v4.1.0-37-gd9362d3 version which was `latest` docker image on https://quay.io/repository/pusher/oauth2_proxy?tag=latest&tab=tags several days ago

**Comment by starkers** [comment] 2020-01-28 15:09
I have had not been able to reproduce the error with the github provider on `master`

![image](https://user-images.githubusercontent.com/462087/73275638-581c8d00-41df-11ea-8cb3-e5bfda3124de.png)

I've tried with and without `-cookie-samesite`for example:


```
./oauth2_proxy \
--client-id=$CLIENT_ID \
--client-secret=$CLIENT_SECRET \
--provider=github \
--email-domain="*" \
--github-org=$MYORG \
--http-address=http://0.0.0.0:8080 \
--upstream=http://localhost:80 \
--redirect-url=http://localhost:8080/oauth2/callback \
--cookie-secure=false \
--cookie-secret=$MY_SECRET \
--cookie-domain=localhost \
--cookie-samesite="none"
```


@amiya-elear  is this possibly an issue with your new provider?  also.. I noticed  `----cookie-samesite="none",` in your report.. maybe something as simple as too many hyphens?

**Comment by JoelSpeed** [comment] 2020-01-28 20:36
@amiya-elear Just had a quick look at your repo, not sure how you created it, but it isn't actually a fork of ours, looks like you've just copy and pasted the contents and created a new commit?

I had a quick look at the code and you are indeed missing the flag on your version of the project
https://github.com/amiya-elear/oauth2_proxy/blob/3412c73892cdacc6ea20d1f3b9426188ddc2c4b2/main.go#L81-L88

You need to copy this line over https://github.com/pusher/oauth2_proxy/blob/d9362d3bb92e610ace7edff59db686783f379a54/main.go#L90

I'm going to close the issue as this is not a problem for us

**Closed by JoelSpeed** 2020-01-28 20:36 UTC
Labels: bug, help wanted, high-priority
